# Generated by Django 5.1.7 on 2025-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patients First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name="Patient's Last Name")),
                ('slug', models.SlugField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=10)),
                ('dateofbirth', models.DateField()),
                ('mobile_number', models.CharField(max_length=11, verbose_name='Patients Phone Number')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(upload_to='images/patients/')),
            ],
            options={
                'verbose_name_plural': 'Patient Info',
            },
        ),
    ]
