# Generated by Django 5.1.7 on 2025-04-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='first_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims_as_patient_name', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='claim',                                                                                                                                                                                                                     
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_as_patient', to='patient.patient'),
        ),
    ]
