# Generated by Django 5.1.7 on 2025-04-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_first_name_alter_claim_patient_id'),
        ('patient', '0001_initial'),
    ]

    operations = [                                                                                                                                                                                                              
        migrations.AlterField(
            model_name='claim',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims_as_patient', to='patient.patient'),
        ),
    ]
