# Generated by Django 5.1.6 on 2025-02-06 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('address', models.TextField()),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/hospital/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_type')),
            ],
        ),
    ]
